# Generated by Django 4.2 on 2024-01-26 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_mappointers_photo_mybooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mybooking',
            name='photo',
        ),
    ]
