# Generated by Django 4.2 on 2024-01-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_mybooking1_delete_mybooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappointers',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
