# Generated by Django 4.2 on 2024-01-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='mybooking1',
            name='var',
            field=models.IntegerField(default=0),
        ),
    ]
