# Generated by Django 4.2 on 2024-01-30 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='booked',
            name='email',
            field=models.EmailField(default='megh.shah2003@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='mappointers',
            name='email',
            field=models.EmailField(default='megh.shah2003@gmail.com', max_length=254),
        ),
    ]
