# Generated by Django 4.2 on 2024-01-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_booked_email_mappointers_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booked',
            name='email',
        ),
        migrations.AddField(
            model_name='mybooking1',
            name='email',
            field=models.EmailField(default='megh.shah2003@gmail.com', max_length=254),
        ),
    ]
