# Generated by Django 4.2 on 2024-02-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_booked_email_mybooking1_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappointers',
            name='booked_by',
            field=models.CharField(default='empty', max_length=500, null=True),
        ),
    ]
