# Generated by Django 4.2 on 2024-02-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_mappointers_booked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappointers',
            name='booked_by',
            field=models.CharField(default='empty', max_length=50),
        ),
    ]
