# Generated by Django 4.2 on 2024-02-06 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_mappointers_booked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mappointers',
            name='booked_by',
        ),
    ]
