# Generated by Django 4.2 on 2024-02-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_mappointers_booked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappointers',
            name='booked_by',
            field=models.CharField(default='None', max_length=500),
        ),
    ]
