# Generated by Django 4.2 on 2024-02-08 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_mappointers_booked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappointers',
            name='Booked_email',
            field=models.EmailField(default='megh.shah2003@gmail.com', max_length=254),
        ),
    ]
